body:
  - type: markdown
    attributes:
      value: |
        You have got an idea how this project could be improved? Let's discuss it!
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: "What is the goal of this idea?"
    validations:
      required: true
  - type: textarea
    id: additional-references
    attributes:
      label: Additional References
      description: "What is the goal of this idea?"
  - type: dropdown
    id: poc-needed
    attributes:
      label: Is a Proof of Concept needed?
      options:
        - "No"
        - Yes, already done (please add a reference)
        - "Yes"
    validations:
      required: true
